# Generated by Django 3.1.2 on 2020-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201025_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='link',
            new_name='gitlink',
        ),
        migrations.AddField(
            model_name='job',
            name='weblink',
            field=models.URLField(null=True),
        ),
    ]
